// <auto-generated />
namespace DataCrowds.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addquestionmodelkey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addquestionmodelkey));
        
        string IMigrationMetadata.Id
        {
            get { return "201605252013147_add question model key"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
